export enum EstadoVenta {
    PENDIENTE = 'PENDIENTE',
    AUTORIZADO = 'AUTORIZADO',
    RECHAZADO = 'RECHAZADO',
    PRODUCCION = 'PRODUCCION',
    TERMINADO = 'TERMINADO',
    DESPACHADO = 'DESPACHADO',
    EN_LOTE = 'EN LOTE',
    ANTICIPADO = 'ANTICIPADO',
  }
  
  export enum FormaPago {
    CONTADO = 'CONTADO',
    CREDITO = 'CREDITO',
    ANTICIPADO = 'ANTICIPADO',
    REPOSICION = 'REPOSICION',
  }